from datetime import datetime

from PyQt5.QtWidgets import QWidget, QGridLayout, QPushButton, QSizePolicy
from PyQt5 import QtCore, QtGui, QtWidgets

from Attivita.GestioneUtenti import GestioneUtenti
from Attivita.Utente import Utente

class VistaDettaglioUtente(QWidget):
    def __init__(self, codice, callback=None, parent=None):
        super(VistaDettaglioUtente, self).__init__(parent)
        self.callback = callback
        self.codice = codice
        self.gridLayout = QGridLayout()

        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel()
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.labelCodice = QtWidgets.QLabel()
        self.labelCodice.setObjectName("labelCodice")
        self.gridLayout.addWidget(self.labelCodice, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel()
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel()
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.labelcodFiscale = QtWidgets.QLabel()
        self.labelcodFiscale.setObjectName("labelcodFiscale")
        self.gridLayout.addWidget(self.labelcodFiscale, 6, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel()
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel()
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 9, 0, 1, 1)
        self.labelTelefono = QtWidgets.QLabel()
        self.labelTelefono.setObjectName("labelTelefono")
        self.gridLayout.addWidget(self.labelTelefono, 8, 1, 1, 1)
        self.labelDataNascita = QtWidgets.QLabel()
        self.labelDataNascita.setObjectName("labelDataNascita")
        self.gridLayout.addWidget(self.labelDataNascita, 5, 1, 1, 1)
        self.labelPassword = QtWidgets.QLabel()
        self.labelPassword.setObjectName("labelPassword")
        self.gridLayout.addWidget(self.labelPassword, 10, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 11, 0, 1, 2)
        self.label_8 = QtWidgets.QLabel()
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.labelCognome = QtWidgets.QLabel()
        self.labelCognome.setObjectName("labelCognome")
        self.gridLayout.addWidget(self.labelCognome, 4, 1, 1, 1)
        self.labelNome = QtWidgets.QLabel()
        self.labelNome.setObjectName("labelNome")
        self.gridLayout.addWidget(self.labelNome, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel()
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel()
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 8, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel()
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 10, 0, 1, 1)
        self.labelUsername = QtWidgets.QLabel()
        self.labelUsername.setObjectName("labelUsername")
        self.gridLayout.addWidget(self.labelUsername, 9, 1, 1, 1)
        self.labelEmail = QtWidgets.QLabel()
        self.labelEmail.setObjectName("labelEmail")
        self.gridLayout.addWidget(self.labelEmail, 7, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton()
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 12, 0, 1, 2)
        self.label = QtWidgets.QLabel()
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 2)

        controller = GestioneUtenti()
        utente = controller.ricercaPerCodice(self.codice)

        self.label_3.setText("Data di Nascita:")
        self.labelCodice.setText(str(utente.codice))
        self.label_6.setText("Codice Fiscale:")
        self.label_4.setText("Cognome")
        self.labelcodFiscale.setText("TextLabel")
        self.label_11.setText("Codice:")
        self.label_5.setText("Username:")
        self.labelTelefono.setText("TextLabel")
        self.labelDataNascita.setText("TextLabel")
        self.labelPassword.setText("TextLabel")
        self.label_8.setText("Email")
        self.labelCognome.setText(utente.cognome)
        self.labelNome.setText(utente.nome)
        self.label_2.setText("Nome:")
        self.label_10.setText("Telefono:")
        self.label_9.setText("Password:")
        self.labelUsername.setText("TextLabel")
        self.labelEmail.setText("TextLabel")
        self.pushButton.setText("Ok")
        self.label.setText("Dettaglio Operatore:")

        self.pushButton.clicked.connect(self.indietro)

        self.setLayout(self.gridLayout)
        self.resize(350, 500)
        self.setWindowTitle("Gestionale Palestra Scherma")

    def indietro(self):
        self.close()
